src/base/UMain.pas

It looks like when we exit the application if it is already running, we enter the finally block which contains logging. We should initialize logging before that.
Care full **untested**!

Quickfix for #6

---

configure.ac

Variable/macro names in m4 are case-sensitive, so all instances of lua_LIB_NAME need to use the exact same name.

Fix detection of lua

---

src/base/UMain.pas
src/menu/UDisplay.pas
src/menu/UMenu.pas
src/screens/UScreenName.pas
src/screens/UScreenPartyPlayer.pas
src/screens/UScreenPartyTournamentPlayer.pas

The hotkey combination of storing names into the template slots is configured to be `Alt`+_`F-key`_. A combination of `Alt`+`F4` results into closing the program on several OS. The hotkey is now switched to be `Shift`+_`F-key`_ (although the old hotkey is kept for legacy support, fow now).
The _switch to fullscreen_ hotkey is setup to be `F11`. The F-keys are also used for restoring a template name in the name input field. F11-hotkey was overriding the template hotkey for F11. This resulted into an unusable 11th slot.
Additional to that, name templates can now only be re-/stored if a Button is selected/active. This might be the only downside. `Q` (for quit) is also now possible in _ScreenNames_.
Tech note:
A method is added which is called in order to query if the current _Display_ should …

Re-usable template names hotkeys. Compatibility to Fullscreen switch

---

src/base/UCommon.pas
src/base/UMain.pas
src/menu/UMenu.pas
src/screens/UScreenJukebox.pas
src/screens/UScreenName.pas
src/screens/UScreenSong.pas

Using SDL2 _SDL_MouseWheelEvent_ and calling legacy code with emulated events.
Not the best solution to re-define the old constants of SDL but it seemed to be the most adaptable code. Otherwise `ParseInput` would require to be re-designed to support fields given by the _SDL_MOUSEWHEEL_ event.
Not sure how well touch control works with this solution. Judging from the lib's doc, it could work just fine out of the box.

Re-implemented MouseWheel scrolling

---

src/base/UMain.pas
src/menu/UDisplay.pas

Enforces mouse-over selection without the need to move the mouse.
By using the mouse to navigate through the menus, returning back to the previous screen wouldn't update the mouse-over selection once the new screen is faded in. In case you open a menu and immediately switch back and already adjusting your mouse location in order to push on another button from the original screen, it won't select the button unless you move the mouse. With this change, once the old screen is fully faded out, the mouse-over selection will adjust where the current/last position is located.
There is a slight lag due to the fading process taking place (and preventing any input). Without screen fading enabled, the selection is updated directly (with a small noticable delay though).
Original (cursor needs to move …

Update cursor on screen change

---

src/base/UMain.pas
src/screens/UScreenJukebox.pas
src/screens/UScreenName.pas

Selection Slide menu element didn't work with mouse wheel due to improper/offset given mouse location on MouseWheel event. On mouse wheel event, this change does provide the current mouse location for a proper `InterActAt` call in UMenu (as example).
By having this fixed, the player name/count/avatar screen does react twice when _scrolling_ the player count slide. This is additionally fixed in this change by checking the `Interaction` selection and only scroll the avatar roulette if the player avator button is selected.
Jukebox was also affected by having a proper mouse location which resulted in switching to move/re-order mode when the list is at the end and the mouse wheel down is sent.
PS: Append `?w=1` to this URL for a proper diff of UScreenJukebox.pas.

Fix mouse wheel on slide

---

src/media/UAudioCore_Bass.pas

The version number is converted from hex to decimal back to hex (in `Format`). This results into a version like `2.4.11.2` (in original hex value) being decoded from the according hex value to the string `2.4.B.2`.

Fix Bass version decoding

---

src/base/UCommon.pas

SplitString wasn't working for simple cases such as `SplitString('800x600', 1, ['x']` which resulted into `'800x60'` or something similar.
Code | |  Result
----- | --- | ------------------
`SplitString('split  me now', 0)` | -> | `['split', 'me', 'now']`
`SplitString('split  me now ', 0)` | -> | `['split', 'me', 'now']`
`SplitString('split  me now ', 0)` | -> | `['split', 'me', 'now']`
`SplitString(' split  me now ', 0)` | -> | `['split', 'me', 'now']`
`SplitString(' split  me now ', 1)` | -> | `['split  me now']`
`SplitString(' split  me now ', 2)` | -> | `['split', 'me now']`
`SplitString(' split  me now  ', 1)` | -> | `['split  me now']`
`SplitString('split  me now  ', 1)` | -> | `['split', ' me now']`
`SplitString(' split  me now  ', 0)` | -> | `['split', 'me', 'now']`
Note: The table …

Fixed and simplified SplitString

---

src/base/UCommandLine.pas
src/base/UCommon.pas
src/base/UGraphic.pas
src/base/UIni.pas

USDX tries to acquire the possible display modes but it still uses fallback resolutions otherwise.
If SDL2 is capable of, it will verify if the desired resolution is in range, otherwise it will either revert back to current desktop resolution or the default one. Once a window is created, USDX will validate the size and possibly remove the currently setup resolution from the available modes list.
On windows: Creating a (windowed) window bigger than the desktop resolution will only create a window with the max desktop resolution.
This is one initial change to the fullscreen mode. Currently, the fullscreen works well using the native desktop resolution but in some cases you really want to fun the game in a specified resolution, for instance having an monitor/TV attached not supporting a …

Use video display modes provided by SDL2

---

game/themes/Deluxe.ini
game/themes/Modern.ini
src/base/UGraphic.pas
src/base/UThemes.pas
src/screens/UScreenMain.pas
src/screens/UScreenParty.pas
src/ultrastardx.dpr

Instead of having a party menu with a slider to select the party mode and change specific sliders accordingly (and eventually switch to another screen) this new screen route the user to a specific mode's options.
This is a WIP screen and will point to the specific screens instead of ScreenPartyOptions. In order to keep the PR small, I just kept everything in place and didn't change any other behavior/look of the party screen. The party options screen should be split into several option screens, for each unique mode its own.
PS: I am actually working on something similar and that's why I made this smaller PR.

Party mode selection screen

---

src/media/UAudioCore_Portaudio.pas

Polling on Mac OS X 10.11 seems to be taking between 450-1100ms. Fixes #119

Increase audio device polling time to 1500ms

---

Makefile.in

As noticed in #137 some data directories did not get installed using the Makefile. This adds the missing directories to the install and the cleanup targets.

Makefile: Add missing data directories

---

configure
dists/autogen/get-ffmpeg-versions.sh
dists/autogen/m4/pkg_config_utils.m4

This are three small patches for the autoconf stuff for the ffmpeg_version handling:
* Replace a shell test with a m4 macro to cleanup the generated configure file.
* Add a script to parse the ffmpeg version ranges from the source files in `src/lib/ffmpeg*/`.
* Update the m4 macro to use version ranges for the ffmpeg check, to fail early with unsupported ffmpeg versions.

Better ffmpeg_version handling in autoconf

---

src/media/UAudioDecoder_FFmpeg.pas

This reverts another part of commit
8f124684198e2a99e69cfc1075890902ddc67521, probably fixing #211

Revert leftover of "audiobuffer requires size of int, not of byte."

---

Makefile.in

As noted by @kamischi, fink has X11 as dependency of ffmpeg, so not copying it breaks the
standalone app.

Re-add copying of X11 when using with fink

---

configure
dists/autogen/m4/pkg_config_utils.m4
src/lib/ffmpeg-3.1/avutil.pas
src/lib/ffmpeg-3.1/libavutil/error.pas
src/lib/ffmpeg-3.2/avutil.pas
src/lib/ffmpeg-3.2/libavutil/error.pas
src/media/UAudioDecoder_FFmpeg.pas

With these commits USDX correctly decodes MP3s with the current FFmpeg 3.2.2 from jessie-backports.

Audio decoding with recent FFmpeg version

---

src/base/UMain.pas

This fixes issues with textinput on SDL2, such as duplicated letters appearing.

Fix textinput for SDL2

---

src/media/UVideo.pas

These commits hopefully fix #118 and #160. The first one is a refactored version of my 0003-use-simpler-pts-reordering-code-with-recent-FFmpeg.patch from [https://sourceforge.net/p/ultrastardx/patches/53/](https://sourceforge.net/p/ultrastardx/patches/53/).

Fix video frame timing

---

Makefile.in
autogen.sh

This adds a message to autogen.sh and simplifies it by using `autoreconf`.
Additionally the Licenses for 3rd party libs are added to the dmg for macOS.

Minor build system changes

---

get-svn-history.sh

As discussed on IRC, the script added by this commit will fetch a replacement ref from the server to fake the history of the master branch to also include the commits done on the old svn repository.
For the script to work, first fetch the ref from my repository and push it into the official repository:
`git fetch https://github.com/s09bQ5/USDX.git 'refs/replace/*:refs/replace/*'`
`git push origin 'refs/replace/*'`
(If you are paranoid, use `c4fc4aaf35a1c6469f747f50afcbac10be9e3342` instead of `*`)

add script to extend history with svn commits

---

src/media/UAudioDecoder_FFmpeg.pas
src/media/UAudioPlayback_SoftMixer.pas

and fix #244.
The changes are done in very small steps to make them easier to understand.
I hope that all locking problems are gone now and there is no delay when waiting for the termination of the parsing thread. The changes have not seen much testing, though.

Change the locking in AudioDecoder_FFmpeg

---

configure
configure.ac
tools/travis/build.sh

The Travis job for OS X installs FFmpeg 2.8 with Homebrew. When ffmpeg28 was moved from homebrew-versions to homebrew-core it was set to keg-only. This makes homebrew omit the symlinks to /usr/local/lib because it would conflict with the unversioned ffmpeg formula. To use FFmpeg 2.8 one has to explicitly look into /usr/local/opt/ffmpeg@2.8/lib. The problem was not noticed earlier because the Travis build script ignores the exit code of configure.
The first commit forces the build script to exit if any command fails. The second commit adds more search paths depending on the OS X package manager. The else branch is just for compatibility.

Fix build of OS X Travis job

---

configure.ac
dists/linux/build-deps.sh
dists/linux/dl.sh
src/config.inc.in
src/lib/midi/DelphiMcb.pas
src/lib/midi/MidiCons.pas
src/lib/midi/MidiConsWin.pas
src/lib/midi/MidiFile.pas
src/lib/midi/MidiIn.pas
src/lib/portmidi/MidiOut.pas
src/lib/portmidi/portmidi.pp
src/lib/portmidi/porttime.pp
src/ultrastardx.dpr
tools/travis/install.sh

This should fix #297.
So far only Linux has been tested. Windows still uses the old code, though it is also supported by PortMidi. I hope I didn't break support for Windows while restructuring the code. A fix for 64 bit architectures is also included. Btw., do we still support compilation with Delphi?

Add MIDI support for other platform

---

Makefile.in
Makefile.osx-helper

This should fix the problem we have with the OS X Travis build, where some libraries (f.ex. libx264) are missing from the standalone application package.

Automatically collect all OS X libraries for standalone package

---

src/base/USongs.pas

This situation may occur in some situations where the FileSystem iterator
produces an empty string. A probably better fix would be to patch this later.
Fixes #309.

Prevent an infinite recursion in FindFilesByExtension()

---

src/base/UFont.pas
src/lib/dglOpenGL/dglOpenGL.pas

We were mixing GL calls from dglOpenGL with GL contexts from SDL and GLU calls from Free Pascal's glu unit with GLU calls from dglOpenGL. This caused problems on at least one dual GPU system where libGL.so did not point to the same library as libGL.so.1, as dglOpenGL uses the former filename and everyone else uses the latter filename on Linux.

Use only a single provider for GL and GLU

---

src/media/UAudioInput_Portaudio.pas

Hi, I think this solves #150, which I think it's also the cause for #221 and #333.
I think the problem was this fixed value of 4 multiplying frameCount, because when I took a look at my mics connected, the AudioInput.FrameSize for them was 2 (but the default Macbook device was actually 4, as the fixed number). So that made things read more buffer than it was actually being written, and thus generating noise (because, I imagine, random bits in that unwritten buffer space).
This seems to make my USB mics work, and my default Macbook audio device also keeps working.
**Disclaimer**: I don't know Pascal, and I don't know about audio processing, so please take a careful look :)

Fix single-channel USB mics on macOS

---

tools/travis/install.sh

As noted in #428 our Travis job for OS X is broken again as the prebuilt ffmpeg@2.8 library from Homebrew has an unsatisfied dependency on libjack.
We do have support FFmpeg 4.1, so let's use it.

Fix Travis on OS X

---

dists/linux/build-deps.sh
dists/linux/build.sh
dists/linux/dl.sh

Will have to research this more, but disabling it is the easiest fix.

Linux: Remove libcwrap from build, it causes errors on some systems

---

dists/gentoo/ultrastardx-2017.8.0.ebuild

The Gentoo ebuilds were severely outdated. Update them so that they work on a current Gentoo.
I did not test the 2017 ebuild, since you need an old ffmpeg (the stable version, running ~amd64 here).

Update Gentoo ebuilds

---

src/base/UMain.pas

This is a fix/workaround for issue #424.
It significantly reduces the amount of question marks displayed when USDX is stared on Linux in an environment that does not select an UTF-8 locale. 
What is not fixed by this commit is that file names still use the code page of the locale. So if you start USDX with LC_CTYPE=C, you can't play songs that have files with non-ASCII characters in their name. There is no way to properly fix this in USDX. It is true that part of the problem stems from the conversion of the RawByteStrings returned by the filesystem functions to UTF8Strings. But eventually USDX has to convert filenames from the UTF-8/CP1250/CP1252-encoded text files to what it believes is the native encoding for file names.

Use UTF-8 strings by default regardless of OS locale

---

README.md
src/screens/controllers/UScreenSingController.pas

Ctrl-Left/Ctrl-Right moves playback cursor 5 seconds forward/back.
This is intended mainly for fine-tuning when making a new song.

Add two undocumented shortcuts for seeking during playback

---

src/media/UAudioInput_Bass.pas
src/screens/UScreenOptionsRecord.pas

So I tried to fix the issue myself because switching to portaudio introduced terrible sound artefacts with certain mp3 files (I'd guess resampling issues).
I think it all works as intended now but since these are literally my first lines of pascal code someone better look over those 4 new lines, rookie mistakes are expected!
I tested it on Windows 10 with multiple sound cards and configurations and it looks fine to me.

Fixes for issue #481

---

src/base/TextGL.pas

glTextWidth is used in various places to center or right justify text. If the left side bearing of the first glyph is subtracted from the sum of all glyph advancements (2nd param of BBox is true), the text is drawn a tiny bit too far right or might extend past the space allocated for it because glPrint will "draw" the left side bearing even for the first glyph. Also note that the glyph advancement includes the right side bearing of the last glyph.
@bohning, this should fix the problem you noticed in the discussion of PR #428 after it was merged.

glTextWidth: don't subtract left side bearing

---

.gitignore
DEVELOPMENT.md
Makefile.in
README.md
configure.ac
debian/control
debian/rules
dists/autogen/m4/ax_cxx_compile_stdcxx.m4
dists/autogen/m4/cmake.m4
dists/gentoo/ultrastardx-9999.ebuild
dists/linux/dl.sh
dists/linux/tasks.sh
src/Makefile.in
src/config.inc.in
src/lib/openCV3/ApiWrapper.cpp
src/lib/openCV3/Makefile.in
src/lib/openCV3/opencv_core.pas
src/lib/openCV3/opencv_highgui.pas
src/lib/openCV3/opencv_imgproc.pas
src/lib/openCV3/opencv_types.pas
src/ultrastardx.dpr
tools/travis/build.sh
tools/travis/install.sh

Fixes #478 
By default the old code that loads the libraries at runtime and uses the C API is used.
To use the new code, pass --with-opencv-cxx-api to configure.
In my opinion this should be used on all current systems if webcam support is desired.
Since the wrapper uses UMat objects, it will not work with OpenCV < 3.0.
The OS X Travis job builds without problems, but the OpenCV libraries from Homebrew use @rpath, which is not yet supported by Makefile.osx-helper.

Add wrapper for OpenCV C++ API

---

src/base/UCommon.pas
src/base/ULog.pas
src/base/UMain.pas
src/media/UAudioInput_Portaudio.pas
src/media/UAudioPlayback_Portaudio.pas

When an exception happens in the finally block of our Main procedure while it was cleaning up another exception, Free Pascal will not report the exception that triggered the finally block to run but only the exception inside the finally block. These commits fix various exceptions inside or after the finally block observed after causing an exception in TPlatformLinux.Init. It should help to uncover the real reason for the premature termination in #505 (which is currently hidden by the exception in the ConsoleHandlerFunc thread). I would not be surprised if the backtrace in #502 also shows this red herring.

Error handling fixes

---

configure.ac

Should fix #462 as long as one uses a shared library that knows about all its dependencies.

Use Lua library returned by pkg-config

---

src/base/UGraphic.pas

Applying the work around from [issue 500](https://github.com/UltraStar-Deluxe/USDX/issues/500) in code form.
The work around forces a video mode update after screen initialization.
Local tests on a MacBook Pro 2019 MacOS 10.15.3, shows the screen no longer shows shifted up in full screen mode, in window mode the screen fills the window instead of 1/4th of the screen.

Fix mac os screen initialization

---

src/media/UVideo.pas

Looping videos starting at 0s were broken since f186fc5bffabce4406d1897c8ef667117ecd11d4.
It is unfortunate that nobody tested this in the 13 months before the release and then someone came along within 14 hours after a release and reported it. Maybe we should upload release candidates next time.
When the first frame of the loop has no PTS or a PTS of zero, the value of fNetFrameTime will be used instead. But that value still was beyond the end of the loop.
Fixes #520

UVideo: Fix looping of videos starting at time 0

---

configure.ac
dists/gentoo/ultrastardx-9999.ebuild
src/media/UAudioInput_SDL.pas
src/switches.inc
src/ultrastardx.dpr

This PR makes PortAudio optional by allowing audio to be recorded using SDL.
Benefits:
- less dependencies on external libraries
- SDL knows how to talk to PulseAudio
Drawbacks:
- SDL might not use the native sampling rate and channel count of the device. In case of PulseAudio the daemon will convert the data to the sampling rate and channel count we request (or to 22050 stereo if we tell SDL to use default values). I will try to file a bug in SDL. SDL has an environment variable that users can user to override the channel count if two channels per device is not enough. We request 44100Hz sampling rate.
- This triggers a race condition in SDL on Linux if SDL fails to open the session or system D-Bus. Audio threads created by SDL try to raise their priority by asking rtkit over D-Bus and …

Allow audio recording using SDL

---

src/base/UIni.pas
src/media/UVideo.pas

The codecs have to be listed in the PreferredCodecs key of the Graphics section of config.ini. They must be separated with comma and/or space.
Example:
```
[Graphics]
PreferredCodecs=h264_mmal mpeg4_mmal mpeg2_mmal vc1_mmal
```
If the list contains an unknown codec name, all possible codecs supported by libavcodec that would not be chosen by default are printed to Error.log when the first video is opened. Since for most formats there is only one codec, this list is usually very short. A codec being mentioned in Error.log does not mean that it actually works. F.ex. the libavcodec included in Raspbian provides a vp9_v4l2m2m codec although there is no V4L2 memory-to-memory device that can decode VP9.
Note that mpeg2_mmal and vc1_mmal require a license key to be bought and VC-1 hardware …

UVideo: allow codec selection

---

configure.ac
src/lib/Lua/ULua.pas
src/lua/ULuaCore.pas

Adding support for the new version was straightforward: vimdiff the 5.3 and 5.4 headers, modify the unit as needed
There are also three fixes in this PR. The first bug prevented 5.4 from working because 5.4 contains additional code in lua_settop to call a function when the stack reaches a specific level. The other two bugs (size_t & LUAL_BUFFERSIZE) might not be triggered by our code.
Fixes #557

Support Lua 5.4

---

dists/flatpak/eu.usdx.UltraStarDeluxe.yaml
dists/linux/dl.sh
dists/linux/dockerenv.sh
dists/linux/lua-relocatable.patch
dists/linux/tasks.sh

As suggested in #565 here some updates for the AppImage and Flatpak builds:
FFmpeg 4.2.4 -> 4.4.1
dav1d 0.8.1 -> 0.9.2
Lua 5.3.6 -> 5.4.3
SDL 2.0.14 -> 2.0.16
SQLite 3.34.1 -> 3.36.0
libjpeg-turbo 2.0.6 -> 2.1.2
OpenCV 4.5.1 -> 4.5.4
Free Pascal 3.2.0 -> 3.2.2
OpenSSL 1.1.1j -> 1.1.1l (only used at build time)

Update deps for Linux builds

---

README.md

Both the URL from which the badge is requested as well as the URL to which it links should now point to the current, relevant AppVeyor projects.

Update AppVeyor build status badge

---

game/themes/Deluxe/Blue.ini
game/themes/Deluxe/Fall.ini
game/themes/Deluxe/Ocean.ini
game/themes/Deluxe/Ribbon.ini
game/themes/Deluxe/Summer.ini
game/themes/Deluxe/Winter.ini
game/themes/Modern/Blue.ini
game/themes/Modern/Winter.ini

This should fix #602
Only the theme `Modern/Blue.ini` had the property `PopUpFG` set, leading to crashes for other themes when entering Options / Record. This sets this value everywhere to the same image as in the working theme since `PopUpBG` is identical, too, and this seems a sensible default accordingly.

Add PopUpFG to themes

---

src/screens/controllers/UScreenSingController.pas

This PR technically changes/fixes multiple things at once:
* fix: simplified code for Solo lyrics
* fix: made code order for Duet lyrics look more like the one for Solo lyrics
* change: less hardcoded colors in Duet lyrics
* change: simplified code for Duet lyrics
_Effectively_, all it does is make Duet lyrics draw in exactly the same way as Solo lyrics, including the ability to be customized with the Jukebox lyrics settings, for all three lyric variants (Regular/Bold/Outline).
If you want to review the code changes, I recommend you go commit-by-commit instead of everything at once.
Reason for this PR: I was doing some theme customizations and it really annoyed me that Duet was essentially unusable when using Regular/Bold lyrics (they would always be black...) and that even when using …

Simplify lyric colors

---

src/screens/UScreenEditSub.pas

Changing the BPM in this way will cause a recalculation of all note timings (start + duration). This differs from adapting the BPM value via +/- which does not change any not timings. The use case for this is to correct wrong BPMs of songs that are otherwise synchronous. A note’s start beat is always rounded up (potentially starting a little later than what would be exact), a note’s duration is always rounded down (potentially lasting a little shorter than what would be exact).

Song Editor: change BPM value via F5

---

src/lib/ffmpeg-4.0/avcodec.pas
src/lib/ffmpeg-5.0/avcodec.pas
src/media/UVideo.pas

These are the two line changes for #621 that on my local machines, more or less double the framerate when using 4k videos, and makes seeking in 1080p much faster. Obviously this comes at higher CPU usage, but it uses CPU that wasn't doing anything anyway.
I can't test this for ffmpeg < 5 (because I don't have it). I don't know since which version this is even supported. Simplest solution would probably some some kind of `{$IF...}` around the statement. The branch is open for maintainers because no idea how to do that.

WIP #621 actually use multithreaded decoding

---

src/screens/UScreenEditSub.pas

The case when the difference between the end of the current line and the start of the next line was erroneously handled by the last else, setting the line break to the start of the next line, while it should be handled just like the cases where the gap is greater than 4, namely 2 beats after the end of the current line.

Fixed fixing line breaks

---

src/media/UAudioInput_Portaudio.pas

In the past I've experienced EAccessViolation crashes during initial loading (there's also plenty of issues about it). These were quite hard to debug, since the Error.log only logs the name of a device if either:
- it fails to load in a way that is properly safeguarded against
- it succeeds
Particular device names this has happened with in the past were (alsa) things named `speexrate` or `vdownmix`, but it can probably happen with any device. Maybe it has bad drivers, or maybe USDX doesn't properly catch something, but either way, because the name never gets printed anywhere, it's near impossible to even make suggestions.
This PR adds an extra line of output in Error.log as soon as the device name is available, so that if the last line of Error.log is a line like that, we at least know …

add logging to portaudio setup

---

src/media/UAudioInput_Bass.pas

similar to #637, this adds some very basic logging when using Bass as AudioInput.
Log entries look like this:
```
STATUS: Attempting to configure InputDevice "Microphone (Steam Streaming Microphone)" [Bass.EnumDevices]
STATUS: InputDevice "Microphone (Steam Streaming Microphone)"@1x44100Hz [Bass.EnumDevices]
STATUS: Attempting to configure InputDevice "Microphone (USB Audio Device)" [Bass.EnumDevices]
STATUS: InputDevice "Microphone (USB Audio Device)"@1x48000Hz [Bass.EnumDevices]
```
I could not find if this had a similar thing for latency like PortAudio does, so I left that out. There's also more code (that could potentially cause issues) after it compared to PortAudio, but regardless, it's still better than _no_ logging at all.

add some basic logging to bass audio

---

README.md

There are some things I'm unsure about (see below for list) but the general aim for this is to simplify the compilation instructions enough that we don't need separate wiki pages for it anymore.
Things I'm unsure of (please comment/correct if necessary):
- The text between `5. Build and Run` and `Compiling...` is nearly unchanged, but I don't know how relevant that still is
- Fedora package list is unchanged wrt #635
- Not sure if _all_ the SDL packages are necessary on Windows
- Does regular `make; ./game/ultrastar` really not work on MacOS?
Most of the installation-related things (like `make install`) are deliberately deleted, since it's generally a bad idea to install things like that. The AUR version already creates a regular package, I don't know that works for other distro's. …

Update compilation instructions

---

autogen.sh
configure.ac

This PR fixes #643 by calling automake if autoreconf (an old one) didn't install the auxiliary files. The warnings emitted by automake (since this is not an automake project) are suppressed.
While at it avoid a warning emitted by autoconf by dropping the useless test that caused it.

Fix Autotools issues

---

appveyor.yml

towards the end of 2022, b7f4de6 implemented a bit of a brute-force solution to the _one_ failing job (Ubuntu2004 x86-32)
this PR attempts to reenable all of them, except very specifically that one job
**DO NOT MERGE THIS YET,** this PR is here so I can find the CI jobs back later, because the flatpak one(s) take like half an hour (I'll create an issue about that later)
EDIT: it works (and the installer, too!)

attempt to only exclude x86-32 Ubuntu2004

---

Makefile.osx-helper

Fixes #609 and avoids that a file provided by Apple becomes part of the application bundle.

Makefile.osx-helper improvements

---

src/media/UVideo.pas
src/screens/UScreenEditSub.pas
src/screens/UScreenJukebox.pas
src/screens/controllers/UScreenSingController.pas

Default to acoLetterBox instead of acoCrop in SingScreen and Jukebox. Toggle video aspect ratio via ’A’ in SingScreen.

Use LetterBox aspect ratio instead of Crop. Toggle video aspect ratio in SingScreen via ’A’.

---

src/base/UDraw.pas
src/screens/views/UScreenSingView.pas

fixes #610
I moved all the timebar-drawing logic to `UScreenSingView` and made it use less variables. It should also properly respect the START value now.
Some edge cases and other things that someone should check on a current USDX before merging:
- if someone Ctrl^Left's a lot during a song with a high START value, the progress bar starts going 'negative'. I consider this more as a bug of being able to Ctrl^Left there in the first place, but it might be a regression compared to current behaviour.
- the progress bar will overflow into the time left (or whatever is in the bottom right) if the song doesn't properly end for some reason. See #600. This is a regression compared to current drawing behaviour.
- running a Medley doesn't draw anything (no progress, no note blocks) but did that …

make the timebar display correctly when using START values

---

src/screens/UScreenEditSub.pas

When I make songs, I mostly use flac and wav these days (because lossless). But because those extensions aren't in the array, it won't show the file when you're working on a song. Or worse, it shows a random file from the whitelisted extensions.
It's fine as long as you don't actually edit the field, but it's a bit annoying.
Same for videos really, most videos from youtube these days are webm.

add some extra audio and video extensions to the editor

---

src/screens/UScreenSong.pas

I'm pretty sure the entirety of chessboard/tile is off-by-one somewhere, but at least this patch makes it so that if you're going to a random song within a selection (eg playlist or search), it will at least be _somewhat_ usable.
known bugs:
* it will still sometimes select the overall first or last song (even if outside the selection). this is especially noticeable if your selection is limited to only 1 or 2 results.
overall though, considering the current behaviour is _completely_ broken, I'd be in favour of getting this merged (been using it in local builds for well over half a year already).
I'll probably eventually end up redoing the entire class this is in anyway, for there's _so_ many other bugs (covers not spawning deselected in most cases, off-by-ones, it not correctly computing …

improve skip to random song in chessboard/tile mode

---

src/base/UMusic.pas
src/screens/UScreenOptionsSound.pas

fixes #497
the pause/starting on SelInteraction is a bit of a hack, but not worse than what the on/off toggle was already doing a few lines up.

play background music at the preview volume level

---

COMPILING.md
README.md

Sure, there are a lot of flags strewn throughout the `dist` folder, but most of these aren't really documented anywhere. It's fine for the generic or really optional stuff, but some things come up in issues and it would be useful to document at least these.
So this list isn't exhaustive, instead it lists the most important (and/or less intuitive) ones:
* `--without-portaudio` because it's in a dozen issues
* `--with-opencv-cxx-api` because webcams (on linux only?) will probably not work at all without this flag

document configure flags

---

dists/ultrastardx.appdata.xml

This xml file contains information displayed in app stores like [Flathub](https://flathub.org/apps/eu.usdx.UltraStarDeluxe). If this additional information is not kept here, I have to patch the file for every release. This PR assumes the next release will be done today.

Add more info to appdata file

---

src/screens/UScreenTop5.pas

While playing with a 9-player hack, I noticed that scores for the last one or two players were not saving. I'm going to assume it has also _never_ saved any scores for the people that are using the already existing 8 or 12-player modes across two screens.
I'm not sure if the `[Game].Players` ini value is the actual number of players, or the index in the array of possible player numbers, but that's something for another day. Long-term that should be the actual number, and any code references to `PlayersPlay` should be replaced with directly referencing the `Ini` class.
The PR'd way of looping through them exists in a few other places as well, so it's probably correct. On my local build, it does now save scores for all 9 players at least.

actually save all player scores in modes with more than 6 players

---

game/config.ini
src/base/UDraw.pas
src/base/UGraphicClasses.pas
src/base/UIni.pas

When merged, this PR will close #671.
I'm going to assume this used to be an option, but considering the screenshot in the above mentioned issue, it looks like it's pretty much abandoned. Considering it's essentially unusable in the current state anyway, I propose to remove it altogether.
This has the side benefit of opening up more refactoring/simplification possibilities in the functions this was used in.

remove Graphics.SingWindow option

---

src/screens/views/UScreenSingView.pas

It has always annoyed me that if you're singing as P2 in a duet (as in, a player that gets the second track), the info lyric bar was pretty much useless. This PR fixes that by having both tracks use the same opacity/alpha.
The biggest issue this tries to address is P2 solo parts being near-invisible if P2 uses a darker color.
Before (P1 = 0.8 opacity, P2 = 0.4 opacity)
After (P1 = 0.6 opacity, P2 = 0.6 opacity)
The I tried other values like 0.7 and 0.65, but then the mixing becomes less good. The screenshots are about the worst case possible since yellow is very bright and blue is very dark, and they don't mix as good as, for example, red and green would. But blue is pretty much invisible on the grey background anyway.
The same colors in a custom theme that has a darker background (P1 = …

make P1 and P2 use the same opacity/alpha in the info lyric bar

---

src/base/UAvatars.pas
src/base/UCovers.pas
src/base/UImage.pas
src/base/UTexture.pas

In some places SDL surfaces were used without checking if allocation succeeded.
Sometimes the pixels of a surface were accessed without locking it.
Avoided a crash in #680 when an allocation failed.

Lock surfaces and check success before use

---

Makefile.osx-helper

A commit to support the remaining uses of the @loader_path placeholder allowed by the macOS dynamic linker.
It fixed building for several people in #679.

Makefile.osx-helper: @loader_path is allowed also in rpath

---

COMPILING.md
README.md

this moves the less-used manual Windows package building (because the CI does that for us already) to a new section at the bottom of COMPILING.md
and then adds more details on how to actually do a release since that's something that has to be done manually. it's not that difficult and most of the time is spent waiting on the CI actually, but it makes life a lot easier.

more detailed release steps

---

game/languages/English.ini
game/themes/Deluxe.ini
game/themes/Modern.ini
src/base/UDraw.pas
src/base/UTexture.pas
src/media/UVideo.pas
src/screens/controllers/UScreenSingController.pas

This is essentially #689 but for the static background images
The additional commits are to:
- change theme `[SingBackground]` color to black (instead of white) because white letter/pillarboxes look really weird
- if a texture is deemed "too large", scale it down in a way that keeps the aspect ratio. this technically loses (a little bit) of information if the texture is only too large in one dimension, but there's (currently) no way of getting the _original_ aspect ratio/dimensions from a resized texture.
EDIT: when merging this, also check if this is on the wiki and if yes, update the text there

Improve background aspect ratio

---

README.md
RELEASING.md

This PR aims to make the Readme a bit more end-user-friendly. I don't intend to (ever) make it dummy-friendly, but I was wanting to place a comment on #631 asking if it was still relevant now that we do flathub releases (for the release versions that is), when I realized it would probably be useful to also direct users to precompiled binaries from the Readme.
This PR does 4 things:
- remove "Development README" from the Readme header (I forgot to commit commit this separately) -- it's now just "UltraStar Deluxe"
- remove the giant text logo in the readme so there's less scrolling until you get to see actual content
- added a new section (and renumbered the others) to point towards the currently known installation methods. These are the same as on usdx.eu.
- moved the "Making a release" …

Improve readme

---

src/screens/UScreenName.pas

reset players back to the (colorized) default avatar if the previously saved md5 hash can't be found anymore. fixes #630

default avatar if saved avatar no longer exists

---

src/media/UAudioDecoder_FFmpeg.pas
src/media/UMediaCore_FFmpeg.pas

Reverts botched attempt to fix audio packets accumulating in memory (which only ever happened with FFmpeg >= 5.0) and fixes it properly.
Fixes #700

Fix leak fix

---

src/media/UAudioPlayback_SoftMixer.pas

On ARM64 macOS floating point exceptions appear to be enabled when the audio callback is called. This causes crashes, e.g. when FFmpeg uses the fcvtzs instruction to convert floating point samples > 1 to integers.
I chose to disable exceptions only temporarily since I assume the overhead is negligible.
Fixes #699

Disable FPU exceptions in audio callback

---

game/config.ini

while testing something I noticed that the default config doesn't really use 'nice' colors:
1. the P1 Dark Blue is _very_ hard to see in the timebar. While #678 makes this worse, this was always an issue
2. the P1 Dark Blue is missing some lighter/even-lighter color variations (as does every color above either 6 or 8 iirc)
This causes great visuals like these:
(I didn't bother getting any points, but it would also show up in those vertical bar things)
This PR aims to solve item number 1 and _sort of_ solve number 2 by changing the default colors for P1-P6 to all be in the first six colors. These are still fairly distinct, result in a functioning timebar, and all of them all colors necessary for the score screen. Some screenshots:
Off-topic 1: I do have an actual fix for the second item in …

use better default colors

---

src/base/UDraw.pas

This commit implements the idea I mentioned in https://github.com/UltraStar-Deluxe/USDX/pull/619#issuecomment-1304618924 to move all calculations done on the vertices to the matrix. According to gprof the time spent in SingDrawOscilloscope dropped by 90%.
On my computer using glVertex2f would be slightly faster that glVertex2s, but I guess that depends on the GPU and its driver.

slightly speed up oscilloscope drawing

---

appveyor.yml

Fixes #726
AppVeyor support wrote:
> We’ll fix that during the next image update.
> 
> In the meantime, please use the following command to update apt:
> 
> `sudo apt update --allow-releaseinfo-change`

AppVeyor: Workaround for Ubuntu PPA repo name change

---

README.md
game/config.ini
src/base/UGraphic.pas
src/base/UIni.pas

For an advanced screen setup it is sometimes handy to force USDX to a dedicated screen position (i.e. on my virtual pinball setup).

Added support for window position in borderless mode.

---

README.md

add wiki link to the (newly added) customization page, and merge the wiki links into a single section.
this was mostly done as a response to #728

redo wiki links in readme

---

src/screens/UScreenMain.pas

I, as well as pretty much everyone that I know has experienced it, _hate_ this 'feature':
- start USDX because the first load can take a while (especially for big collections on rotating disks)
- go do something else in the meantime
- after 1 or 5 minutes get blasted by the credits at full volume
I've also seen people teach themselves to never ever let the game idle on the main screen, so instead they'll let it idle in the player selection screen.
Or, we can just get rid of it altogether. This doesn't remove the (probably very outdated) credits (you can still access them through About -> Credits), it just stops them from auto-starting when idling the main menu.

disable the automatic credits on the main screen

---

src/screens/UScreenName.pas
src/screens/controllers/UScreenSingController.pas

See also #732 
This is by no means a complete fix, but if you're currently using players that don't have a microphone and start a song:
old behaviour:
- show the warning _every time_ a song is started
new behaviour:
- show the warning _once_ if you've been on the player selection screen. this covers both routes (from the main menu or through `M` -> Change Players on the song selection screen).
Because unless you've been through the player setup screen, there is absolutely no way this will have suddenly been fixed between songs. Not sure if this also survives disconnecting microphones, but the game doesn't like that anyway. Plus, if the game _does_ handle it gracefully _and_ you haven't had the warning yet, you should actually still get it!
Obviously it will also still show it again if you …

less warnings about players without microphone

---

src/screens/UScreenEditSub.pas

fixes #721.
The `SDLK_*` form was always fine under Linux and Mac. Changing it to use `Ord(CharCode)` makes it still work on those platforms, but also fixes it Windows (though I don't know _why_ this fixes it)
I went through the code and also looked into where else this was used, it's only in two places: `UScreenJukebox` and `UScreenJukeboxOptions`. The former shows up as 85% comment in my editor, making it really hard to figure out what's going on. The latter is easier but if I change only that one it seems to break in really weird ways again. But there are a lot of other things wrong with the Jukebox (just going into it appears to have reset microphone assignments?) that I'm not very motivated to fix the keybinds there.
So this PR only fixes the editor.

use Ord(CharCode) instead of SDLK_*. fixes #721

---

src/menu/UMenu.pas

because then the UI (mostly some navigation bars) gets rendered over them instead of behind them. fixes #604
This fixes at least: SongScreen (when using Roulette) + Options Advanced + Options Game and appears to have no impact on other screens. I did go through most other screens and did notice anything, but it's possible I missed some super obscure thing somewhere.

fix UI drawing order

---

src/screens/controllers/UScreenSingController.pas

fixes #86 
make fading from sing screen to score screen much nicer by unloading the video later
maybe it'll still show the background image for a fraction of a second if you disabled both the background + video by pressing `V` during a song. did not test visualizations.
demo video:
https://github.com/UltraStar-Deluxe/USDX/assets/5775429/060711de-4092-4337-be92-e8a1ff4073ef
for at least videos or background images it will just use whatever was on the last frame.

nicer fading

---

game/languages/English.ini
src/screens/controllers/UScreenSingController.pas

fixes #747 
Current functionality: `S` can skip the _intro_ of a song (but only if the GAP is properly set and the first note is at or near beat 0).
This PR enhances that functionality in the following ways:
- Skip intro on any song: it is now timed relative to the start of the first _note_
- Skip long breaks in songs (this one only works if the linebreak has already occured -- ie it doesn't work if the linebreak is at the _end_ of the long break)
I've also removed explicitly setting the video time because that appears to resync to the audio anyway.
A video to show how OP this is:
https://github.com/UltraStar-Deluxe/USDX/assets/5775429/de804c5e-5893-4b07-a05c-be3fb55e711e
I press `S` at 4.3 and 27.8. The jump at 14.2 is because I paused the recording while I was skipping ahead in the …

S skips more

---

src/base/USingScores.pas
src/base/UTexture.pas
src/base/UThemes.pas
src/menu/UMenu.pas
src/screens/UScreenJukebox.pas
src/screens/UScreenName.pas
src/screens/views/UScreenSingView.pas

fixes #697 
This PR is split across three commits:
1. a very big commit that takes as input the lines which are giving errors in Error.log, and introduces some extra types that only have the elements which are actually _used_ by the code. It also makes some theme elements "optional" in the sense that not defining it isn't actually an error at all, all it means is that some element isn't drawn.
2. stop the `Could not load texture: ""` spam. It just means no texture was set for some element, but tha's fine if you're just drawing colored squares or something.
3. remove the log error for "no texture type set" because in that case it's defaulting to PLAIN anyway
The _entire_ theme loading log now looks like this:
```
STATUS: Loading: /home/bbq/gits/Ultrastar/USDX/game/themes/Deluxe.ini …
```

Less theme errors

---

game/languages/English.ini
src/base/UMusic.pas
src/media/UAudioPlaybackBase.pas
src/media/UAudioPlayback_Bass.pas
src/media/UAudioPlayback_SoftMixer.pas
src/screens/UScreenSong.pas

fixes #748 
removes both the stuff directly related to `K`, as well as the now-unused underlying infrastructure (in separate commits).
I've left in a now-empty `procedure DSPProcHandler` because searching the codebase for `dspproc` turns up a dozen or so results and I don't know this works.
Tested only on Linux, I can do the Windows one once the PR artifact has built and hopefully someone can also check this on Mac (since this touches stuff that could be platform-specific)
EDIT: make sure to also edit https://github.com/UltraStar-Deluxe/USDX/wiki/Controls#shortcuts-for-song-selection-screen when merging this

Remove k voiceremoval

---

RELEASING.md

This updates some release information:
- also update the `releases` branch, fixes #735 
- update the Mac version number, see #744 and PR #745
- some miscellaneous improvements
Do not merge this before 745

Improve release documentation

---

src/base/UDraw.pas
src/base/USingScores.pas
src/base/UThemes.pas
src/screens/views/UScreenSingView.pas

This PR generally changes nothing, except for two 'breaking' changes. The quotes are deliberaty because the breakage only applies to 5 out of 7 elements, so it never applied to the other 2.
What it breaks is that you will now have to define the `SingP1TwoPStatic` and `SingP1ThreePStatic` (and related) sections. Previously if these weren't defined it would just fall back to `SingP1Static` but considering this fallback never worked for the SingBar and the Oscilloscope anyway, so I don't think it's really an issue.
If you want to review this, look for the quite obvious commit message.
For the rest it just massively simplifies `UThemes.pas`, other files only have updated references. Those are for a future PR.

Simplify theme loading

---

src/base/UUnicodeUtils.pas

Currently, the search field (a.k.a. jump to) does not allow entering this apostrophe because it is neither recognized as alphanumeric nor as punctuation character.
This PR adds the typographers apostrophe (’) to the list of punctuation characters to allow searching for songs that use this apostrophe (e.g. "Let’s Twist Again").

Add the typographer’s apostrophe (U+2019) to the set of punctuation characters

---

src/base/UMusic.pas
src/base/URingBuffer.pas
src/media/UAudioDecoder_Bass.pas
src/media/UAudioDecoder_FFmpeg.pas
src/media/UAudioPlaybackBase.pas
src/media/UAudioPlayback_Bass.pas
src/media/UAudioPlayback_SoftMixer.pas

fixes #750 
I changed it to PByte in the one place I knew needed to be changed, then just propagated from the compile errors from there. I tested on Linux and Windows, no idea about Mac (you'll know at compile time -- maybe Mac uses some file that never gets compiled on the other platforms).
This needed changes in quite a lot of places (all of which seem to have buffer size parameters though, so it _should_ be fine?).
I've deliberately not included the fixes for the Makefile, see #786.

Fix audio playback buffer

---

src/screens/views/UScreenSingView.pas

It sometimes upsets the range checking enabled with fpc's -Ciro.
Fixes #786

UScreenSingView: fix uninitialized float being used

---

src/media/UAudioPlayback_SoftMixer.pas

In #656 the code for using libswresample was fixed. This commit enables it and prefers it over the SDL resampler.

SoftMixer: use libswresample if available

---

src/base/USingScores.pas

the function as a whole is still way too big, but at least it's now _less_ big.
the popup is the awful/awesome/etc thing that pops up at the end of every sentence. I have _no_ idea what 2 player duet is even doing (it's only drawing it for player 1?) but it's also doing that in current master, so it's not something caused by this branch.
I deliberately did not touch whitespace/indents. Much of this function as a whole is still a mystery to me, and I'm going to do similar refactorings in other places before I'll even attempt unravelling it.

refactor some DrawPopup internals

---

autogen.sh

usecase:
bohning PM'd me that something in his build system had broken and `configure` nor `autogen.sh` were fixing it. was probably some permission issue (not worth looking into further) but while looking into it it would have been useful if I didn't have to pull up man-pages to figure out what `autogen.sh` was _supposed_ to be doing in the first place.
there's really no reason to use short options for these kind of things.

use full option names instead of the 1-letter options

---

.gitignore
src/base/ULyrics.pas
src/screens/controllers/UScreenSingController.pas

There's a bug where when you restart a song that's being played (using the 'r' key by default) the lyrics will no longer show correctly until the song catches up to the point at which it was restarted.  This PR fixes that.

reset the active lyric line's progress when restart command is invoked

---

src/screens/UScreenSongMenu.pas

fixes #810
basically just a forgotten case from #782.
NB you (still) can't use the letter `q` in new playlist names, see #812 for that

allow text input for new playlist names

---

.gitattributes

When looking at the raw diff, most hunk headers in Pascal source files are currently literally `begin`, which doesn't really say anything useful.
Adding this .gitattributes changes that to print the function the change is in. This won't affect any actual `git apply` of diffs (it's just a comment for humans) but it makes it a lot easier to understand where we're changing things.

add .gitattributes to have more descriptive git diff hunk headers

---

src/base/USong.pas

fixes #746
this makes it so that USDX will outright refuse to load songs that rely on the current behaviour for duets where if you have sentences for P3, they'll end up in both P1 and P2. instead it will now log an error for that txt in Error.log:
```
ERROR:  Wrong P-Number in file: "duetp3hack.txt"; Line 396 (LoadSong)
ERROR:  AnalyseFile failed for "/home/bbq/gits/Ultrastar/USDX/game/songs/songs_extra_some_pony/The Count of Monte Cristo - I know those eyes/duetp3hack.txt".
```
this has been announced as a future breaking change in the release notes of 2024.3.0, but I don't think it'll affect that many people anyway. refusing to load it makes it so that you also can't accidentally delete the shared parts from the editor. a workaround for people that still rely on it will be provided in …

remove P3=P1+P2 duet hack. fixes #746

---

dists/linux/projectM-2.2.1.patch
dists/linux/tasks.sh

That patch was used by more than just the flatpak build.
We didn't notice so far because the result of the projectM build was cached by AppVeyor.

Restore projectM Patch removed with 1936e7fee914

---

dists/linux/build.sh
dists/linux/scan_libs.sh
dists/linux/tasks.sh

This redefines tput to an empty function if it would fail when called with the parameters later used in the script.

AppImage: avoid build failure due to TERM variable

---

.github/workflows/main.yml
Makefile.in

This adds a build for MacOS on ARM. The `codesign` call is necessary for the ARM build, as that version requires apps to be signed, and prevents execution otherwise.
I don't have a Mac, but had people confirm that both the MacOS 13 and MacOS 14 build run fine.

CI: implement build for MacOS 14 (ARM build)

---

.github/workflows/main.yml

Another day, another CI fix...
This hopefully fixes the super-flaky Windows builds. I've tested that the Windows installer built in the CI with NSIS 3.05 works 
Background:
As part of the Windows CI, we so far downgraded the installed NSIS version on the runner from 3.10 to 3.04, which is the version used by AppVeyor. Version 3.06 introduced a bug that made the installer crash after language selection, and a later version seemingly introduced another bug that made the installer crash even before that.
It seems like there's something going wrong with the down-grading process _some of the time_, as the random build failures complain about a missing function (`LoadAndSetImage`) that was only added in NSIS 3.05.
For now, I've tried repeating CI runs for both 3.04 and 3.05. The former led to a …

CI: upgrade to NSIS 3.05

---

src/lua/ULuaCore.pas

Hi all
I just came up with this addition. This is useful if the plug-in wants to load additional resources relative to its location.
This is approach is quite daft. For a more intricate solution, we could also create a table with all the paths from `UPathUtils`. I am up for discussion. What do you think?
Kind Regards
Hermann

Make current file name known to the plugin.

---

src/media/UAudioConverter.pas

Should fix #860, but I only checked if the timestamp progresses at the correct speed since I am currently sitting in a train and don't have headphones. Please test if it breaks files that were playing correctly.

AudioConverter: fix output buffer size calculation

---

src/screens/UScreenSong.pas
src/screens/UScreenSongJumpto.pas

Instead of picking a random song whenever R is pressed, this generates a random permutation of all songs, goes to the next one in that order every time R is pressed, and finally generates a new permutation once all songs have come up once.
While in a search, this creates a random queue based on the filtered subset of songs. This queue is reset whenever the search filter is changed.
Depending on what your expectations are, I would say this resolves #186
I have only implemented this for the regular randomization (the "in one category" case) since I have no idea what the category feature does or how I can access it...

Do not repeat songs when randomizing

---

RELEASING.md
dists/ultrastardx.appdata.xml

The latest FlatHub build failed due to some lint errors on the AppStream file:
https://buildbot.flathub.org/#/builders/7/builds/15587/steps/11/logs/stdio
These were the required fixes:
- Add developer tag (https://docs.flathub.org/docs/for-app-authors/linter/#appstream-missing-developer-name)
- Shorten the summary to be less than 35 characters. Someone might want to suggest something more exciting than "Karaoke for your PC", but 35 characters isn't much to work with! (https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines/#summary)
- Add captions to screenshots (https://docs.flathub.org/docs/for-app-authors/linter/#appstream-screenshot-missing-caption)
- Rename `recommended` tag to `recommends` and remove "keyboard" from `supports`. Each value can only appear …

Update AppStream file to meet FlatHub requirements

---

src/base/UDraw.pas
src/base/UGraphic.pas
src/screens/UScreenEditSub.pas
src/screens/views/UScreenSingView.pas

Before, the selected bar would use P2's color to mark the selected bar. This leads to no marking at all when no color has been selected for P2.
The color attribute for each bar currently holds only a single integer for the player number, since this reuses the coloring-mechanism of the actual sing mode. I chose to mark the selected syllable as belonging to player 99 (instead of player 2) and then making a distinction for that number. The choice is arbitrary, I just didn't want to use 0 since it seems to be already used for something else.
Currently, the color used for marking is the inversion of P1's color. We could also change this to not be based on the player colors at all, and instead use two fixed colors for selected/not selecte or similar.

Use P1 inverted color to mark selected bar in editor

---

src/base/UFiles.pas
src/base/USong.pas

fixes #859 
only `#RESOLUTION` 1 or higher is now considered valid. if an invalid resolution is encountered, it will log the following line in Error.log at startup:
```
ERROR:  Ignoring invalid resolution in song: /path/to/notes.txt
```
and internally just use the default. It will not modify the file directly, but when saving from the Editor, the illegal line will be permanently removed.
First commit fixes the problem, second commit is some housekeeping to reduce duplicated hardcoding.

Ignore invalid #RESOLUTION

---

.editorconfig
.github/workflows/check-whitespace.yml

The editorconfig should prevent trailing whitespaces and ensure a trailing newline in all files.
The CI adds another job that runs on PRs only, marking all spots in `src` (though ignoring `src/lib`, `src/webSDK`) changed in that revision that added trailing spaces. An example of the output in case of failure can be seen [here](https://github.com/UltraStar-Deluxe/USDX/actions/runs/10111040317/job/27962189639).
This encompasses stage 1 & 2 from #873 
Open question: Should the .editorconfig apply to all files, or should we limit this to the same folders as the CI check?

Add .editorconfig and CI check for trailing whitespace

---

COMPILING.md
README.md

document the --enable-debug flag for configure because it makes debugging EAccessViolation on at least Linux platforms possible

document the --enable-debug flag for configure

---

dists/linux/Dockerfile.in

Seems like the EPEL URL has been quietly changed to archives *separately* from when they moved the entire repo over, see [here](https://dl.fedoraproject.org/pub/epel/7/README).
This PR changes the download URL used by the dockerfile to point to the last release (EPEL 7.14) in archives instead.

Fix EPEL download URL in dockerfile

---

src/base/USingScores.pas
src/screens/UScreenSong.pas

I was looking through my local diff and found some more areas where my 9-player modification is creating giant walls of duplication.
Also fixed a few other ones along the way. Most notably this PR adds a TODO in `TScreenSong.SongScore` because something feels off about those equations.
None of what this PR does should change any existing behaviour.

Refactorings in USingScores and UScreenSong

---

.github/workflows/main.yml

Builds are triggered on pushes to the repo and when a PR is updated. If a PR from a branch in the same repo is pushed to, both triggers activate, starting each job twice.
This change guards against this case by limiting push-builds to the master branch, at the cost of not triggering CI builds for pushes to other branches in the repo, if there is no PR for them.

CI: prevent duplicate triggering of build workflow

---

.github/workflows/main.yml

Un-silence newpascal download and extraction.
Use sourceforge's automatic mirror selection.
See #894

 CI/Windows: fix sourceforge download timeout

---

.github/workflows/main.yml
dldlls.py

As remarked in https://github.com/UltraStar-Deluxe/USDX/issues/889#issuecomment-2337573625 there is a problem when downloading DLLs.
Merge requests from other repositories will not have access to the secret used for the ARTIFACT_ACCESS_TOKEN environment variable. The variable will be set to an empty string. Using an empty token in the Authorization header makes Github reject requests which would be allowed without that header.
If the ARTIFACT_ACCESS_TOKEN is not available, try the GITHUB_TOKEN to avoid the throttling of requests without authorization. It won't work for downloading artifacts, though.

Fix downloading of DLL releases

---

src/base/UMusic.pas

All users of HasLength use the return line duration as divisor. To avoid division by zero, set the result to false if the duration is 0.
Fixes #858

UMusic: Consider line duration 0 as no duration

---

src/base/UThemes.pas
src/screens/UScreenName.pas

some cleanup around GetPlayerLightColor vs GetPlayerLightColorV2.
also fixes a long-standing bug where if P1 or P2 in duets had picked one of the later colors (for example Flame), their lyrics would be colored blue instead of their own color. It now picks the correct color.

cleanup GetPlayerLightColor vs GetPlayerLightColorV2

---

RELEASING.md
UPDATING-DLLS.md

this PR tries to capture what was written in this comment: https://github.com/UltraStar-Deluxe/USDX/pull/889#issuecomment-2326626847
in a way that I (or anyone) can find this back a year from now
most notably
* I merged steps 5 and 6 into a single step, because from how I understand it, we should make the pre-release pretty much _as_ we merge the USDX PR? all the previous steps _can_ have some time between them and it won't break anything
* I made step 7 into its own little section as that is something that isn't really connected to the original updates anymore. You're also doing it as part of releasing USDX itself, so it is a little bit more verbose. I'm not sure if it's 100% correct because we've never done that, but it's better than nothing.
@s09bQ5 the thing I'm most unsure of is …

document DLL updates

---

dists/linux/dl.sh
dists/linux/tasks.sh

Updates
SDL2_image to 2.8.2
SQLite to 3.46.1
dav1d to 1.4.3
FFmpeg to 7.0.2
Lua to 5.4.7
libpng to 1.6.43
OpenCV to 4.10.0
i.e., apart from OpenCV, the same versions used by our Windows build.

Update dependencies for Linux AppImage

---

.gitignore

Since #889, running dldlls.py creates a bunch of untracked files on Windows. these hinder development, so gitignore the resulting files.

less untracked files on Windows

---

src/screens/UScreenEditSub.pas

Remove several unused parameters, simplify the code and improve readability. This also fixes two long-standing problems.
The tone marker was previously always three or four halftones too high. It is now on the same height as what is actually sung.
Previously, the marker was shifted by one octave whenever a new one was entered, e.g. when going from a B2 to a C2, the marker would jump down by 11 halftones. This is changed to always be in the octave that is closer to the current note, i.e. at a distance of most 6 halftones above or below.

Refactor DrawPlayerTrack

---

src/screens/UScreenEditSub.pas

Previously, during editing, switching to a different note via right/left arrow keys adds an undoable entry, making the action revertible via Ctrl+Z and asking whether changes should be saved when quitting.

Do not mark edited file as dirty when selecting note

---

src/screens/controllers/UScreenSingController.pas

An alternate fix for #844 
This probably obsoletes #903 but I'll give @DeinAlptraum a chance to test it first
Some random Pascal that probably describes better what this PR does:
```
writeln ('OLD BEHAVIOUR');
writeln(Floor(989.499 / 10) * 10); // 980
writeln(Floor(989.500 / 10) * 10); // 980
writeln(Floor(999.499 / 10) * 10); // 990
writeln(Floor(999.500 / 10) * 10); // 990
writeln(Floor(999.999 / 10) * 10); // 990
writeln('NEW BEHAVIOUR');
writeln(Floor(Round(989.499) / 10) * 10); // 980
writeln(Floor(Round(989.500) / 10) * 10); // 990
writeln(Floor(Round(999.499) / 10) * 10); // 990
writeln(Floor(Round(999.500) / 10) * 10); // 1000
writeln(Floor(Round(999.999) / 10) * 10); // 1000
```
If it's supposed to go to a 1000 at 995 already, we can change that again in a future PR if needed. …

fix scoreline bonus only allowing values up to 990 instead of 1000

---

src/base/UFilesystem.pas

fix #837 
there are some other places where a `TSearchRec` is used, and we should probably also start getting rid of some of the `RawByteString` stuff because it's just asking for trouble, but _short-term_ this should at least allow people on Windows to load all their songs again.
does not appear to have any effect on Linux, hence no ifdef guards.

fix special characters in file and folder names

---

.github/workflows/main.yml

This prevents one failing build from cancelling the other.

CI: Deactivate fail-fast for Mac builds

---

.github/workflows/main.yml

Several users have reported in the past to be confused about which artifact they should download from the release page for their platform. This change unifies the artifact naming and ensures that the platform name is part of the artifact filename, following the format `UltraStarDeluxe-<platform>[...]-<version>`

CI: rename artifacts to better differentiate platforms

---

src/base/USong.pas

Hello there,
I saw the comment in #789 from @barbeque-squared about how the current tag reading and evaluation in USong.pas should be changed to allow future extensions, especially with regard to handling different txt versions in the future.
Based of the comment I changed the `ReadTXTHeader` function to first read all tags into a `TFPGMap` and afterward evaluate the tags from the map.
I hope this can be a good starting point to allow different tag handling logic depending on the txt version.

Split tag reading and tag handling logic

---

dists/linux/Makefile
dists/linux/dl.sh
dists/linux/tasks.sh

I didn't see zsync actually being used anywhere, so attempt to build without it.
See #931

Remove zsync

---

src/lua/ULuaScreenSing.pas

the array size for the lua functions has no relation whatsoever with IMaxPlayerCount, they currently just happen to be the same value
this is a similar change to what was done in #554, specifically https://github.com/UltraStar-Deluxe/USDX/pull/554#discussion_r571429805
I don't think it's wrong to use a hardcoded number here: it's a static array, it seems to be how Pascal works, it's done _hundreds_ of other times throughout the code -- see for example UIni.pas.
And maybe there is an even better way, but at the very least, I think this PR objectively improves the code.

hardcode lua array size

---

src/base/UIni.pas

As commented on #634, specifically https://github.com/UltraStar-Deluxe/USDX/issues/634#issuecomment-1872986306, 8 and 12 players have never worked at any point in USDX history.
This PR removes the 8 and 12 player options from the player select screen altogether.
EDIT: as the also added TODO suggests: I did not touch the internal IMaxPlayerCount. I don't have the time to figure out which of the 100+ usages is causing issues, and it's one of those things that might just get accidentally fixed during a refactoring.
(I did not have much time in the second half of 2024 to continue the refactoring)

remove 8 and 12 player options from the player selection screen

---

src/media/UAudioDecoder_FFmpeg.pas
src/media/UAudioPlayback_SoftMixer.pas

I added some new songs to my library recently, and encountered #600 for the first time. After some debugging, I have discovered the root cause. I have found that there are actually two different issues causing this, the first in `TFFmpegDecodeStream`, and the second in `TGenericPlaybackStream`. This is why this problem only impacts the Linux/Mac versions (the Windows version uses BASS for both audio decoding and playback).
The first issue is relatively straightforward. For some files, the FFmpeg parser thread is not sending the EOF status packet, and is sending an error status packet instead. The [current FFmpeg code](https://github.com/UltraStar-Deluxe/USDX/blob/fc15e33ee3d847cb38e77e8789b18627738ba44e/src/media/UAudioDecoder_FFmpeg.pas#L861-L907) uses a hack method to detect EOF. This …

More Reliable EOF Detection

---

src/lib/ffmpeg-4.0/avcodec.pas
src/lib/ffmpeg-4.0/avformat.pas
src/lib/ffmpeg-5.0/avcodec.pas
src/lib/ffmpeg-5.0/avformat.pas
src/lib/ffmpeg-6.0/avcodec.pas
src/lib/ffmpeg-6.0/avformat.pas
src/lib/ffmpeg-7.0/avcodec.pas
src/lib/ffmpeg-7.0/avformat.pas
src/media/UAudioDecoder_FFmpeg.pas
src/media/UMediaCore_FFmpeg.pas
src/media/UVideo.pas

A significant breaking change is coming to the FFmpeg API in the [next major version bump of libavcodec](https://github.com/FFmpeg/FFmpeg/blob/539cea31830e71f1ce290c56ff2d639b209c2ac2/libavcodec/version_major.h#L40), which is expected to occur with the release of FFmpeg 8 sometime in the next few months. See #778 for more details.
- sizeof(`AVPacket`) is being removed from the public ABI. The FFmpeg developers want to add fields to the end of the struct without bumping the major version. This means that calling applications should not allocate the `AVPacket` structure, but instead use `av_packet_alloc` to let FFmpeg allocate it. Otherwise, there is a risk of a segfault.
- `av_init_packet` is being removed (`av_packet_alloc` takes over this functionality).
- `AVPacketList` is being removed …

Switch to new FFmpeg AVPacket API

---

src/base/UFiles.pas
src/base/USong.pas

This PR implements support for the UltraStar File Format 1.0.0.
Most notably, `TSong` was extended by the public field `FormatVersion`, which represents the version of the songs txt file file as indicated by the VERSION header. (The absence of the VERSION header is evaluated as a legacy version 0.3.0.)
The file format 1.0.0 removed a few headers, which USDX will now ignore if they are found in a file with VERSION >= 1.0.0. These headers are:
- DUETSINGERP1 / DUETSINGERP2
- RESOLUTION
- NOTESGAP
- ENCODING (For VERSION >= 1.0.0 the UTF-8 encoding is enforced)
- RELATIVE (Songs with VERSION >= 1.0.0 and RELATIVE header are rejected)
I also updated the Song saving code, to handle songs with VERSION >= 1.0.0 slightly differently:
- The VERSION header is written as first header of the file
- …

Implement UltraStar File Format 1.0.0

---

src/lib/ffmpeg-4.0/avformat.pas
src/lib/ffmpeg-5.0/avformat.pas
src/lib/ffmpeg-6.0/avformat.pas
src/lib/ffmpeg-7.0/avformat.pas
src/media/UMediaCore_FFmpeg.pas

For some file formats (notably MP4), FFmpeg uses an `AVStream` structure to logically represent embedded cover art. USDX's current video stream selection logic always selects the first video stream reported by FFmpeg. If the first video stream is cover art, USDX will fail to play the video. See #902.
FFmpeg sets a flag `AV_DISPOSITION_ATTACHED_PIC` to indicate that an `AVStream` object represents cover art. This PR updates the stream selection logic to reject video streams that have the flag set. This ensures that an actual video stream will be selected for files that contain embedded cover art.
Fixes #902

Support Video Files That Contain Embedded Artwork

---

src/base/USong.pas
src/screens/UScreenEditSub.pas
src/screens/views/UScreenSingView.pas

this PR allows songs that only have a single sentence to be played and edited. Previously, these would not be loaded and have a `Can't find any linebreaks` error in the logs.
I'm pretty sure the singview can do without the check altogether (the "endless loop" comment has always been there since the beginning of the repo, but even if you manage to get a song with 0 sentences in, it should still be fine?). Not sure about the editor as it's doing divisions, hence I made it `if < 1` there. Besides, not sure what's the point of editing a song that has no sentences.
fixes #895

Allow songs that only have a single sentence

---

RELEASING.md

In #935 it was found that some release steps were incomplete/slightly off. This PR corrects that.
Also updated the section on failed jobs, as that was for AppVeyor (where we couldn't retry jobs) but on Github we can just retry until It Works.

Update release documentation

---

src/lib/ffmpeg-4.0/avcodec.pas
src/lib/ffmpeg-5.0/avcodec.pas
src/lib/ffmpeg-6.0/avcodec.pas
src/lib/ffmpeg-7.0/avcodec.pas
src/media/UAudioDecoder_FFmpeg.pas

This is the first of two PRs intended to resolve USDX's audio seeking accuracy issues (#673, #749, #884)
This PR significantly improves the seeking accuracy for the FFmpeg audio decoder. The existing seeking method can only seek to points *between* `AVPacket` structures returned by the demuxer. The new method can seek an exact audio sample *within* an `AVPacket`, using FFmpeg's `AVPacketSideData` API. Here is a summary of the changes:
1. Change the seek flag to `AVSEEK_FLAG_BACKWARD`. This ensures that if no `AVPacket` has the exact timestamp requested (which is typical), then the seeking function will select the closest `AVPacket` with a timestamp *less* than the seek target. This means that the seek target will be contained somewhere inside of the `AVPacket`'s compressed audio data
2. …

More Accurate FFmpeg Audio Seeking

---

src/screens/UScreenOptionsThemes.pas

Steps to reproduce the crash:
1. Go to Options->Record
2. Set the 'Assigned Player' for the current device to 'None'
3. Go to Options->Themes
4. Change to a different theme
5. Go Options->Record
Stacktrace:
```
Exception class: EAccessViolation
Message: Access violation
$0000000000542901  DRAW,  line 813 of screens/UScreenOptionsRecord.pas
$000000000045FABA  DRAW,  line 379 of menu/UDisplay.pas
$000000000047A432  MAINLOOP,  line 344 of base/UMain.pas
$000000000047A1C6  MAIN,  line 269 of base/UMain.pas
$00000000004074A7  main,  line 386 of ultrastardx.dpr
```
The crash occurs [here](https://github.com/UltraStar-Deluxe/USDX/blob/2603abcc3aa70b57ede2348761bf641449b3e307/src/screens/UScreenOptionsRecord.pas#L813) because `DeviceCfg.ChannelToPlayerMap` is nil.
The reason is that changing the …

Fix Record Options Crash After Changing Theme

---

src/base/UIni.pas

The problematic lines were referencing `I` outside the loop. I assume this gets compiled differently on different platforms, because it never triggered for me (Linux). To reproduce I had to hardcode the deleted lines to read from `P12`.
Either way, I've made the default colors an array of numbers that just happen to be in the desired order. Downside is it's one more thing to change if we ever increase `IMaxPlayerCount` but that's not happening soon anyway. And at least I put the array directly below it,
I will tag some people to test this once the artifacts are built, because I cannot verify if this fixes it _for them_ as well.
fixes #958

fix default player colors, we should not reference I outside the loop

---

RELEASING.md

if the artifact is not a zip, github will always zip it for you. but we don't want those pointless zips on the release pages, so document that they need to be extracted.
also add a copy-paste oneliner that will work most of the time
(I used to be able to just "Extract Here" but that gives like three popups nowadays. the oneliner is trivial but at the same time enough effort that I don't want to have to retype it every release)

when releasing, all zips except the portable need to be extracted

---

src/media/UAudioDecoder_FFmpeg.pas

As discussed in #968, the BASS playback stream expects the decoded audio stream to be in either 16 bit signed integer or 32 bit float format. Currently, the FFmpeg audio decoder has built-in resampling support, but it only does planar to packed conversions. It doesn't do any bit depth conversions.
This PR changes the behavior of the FFmpeg decoder in the Windows version so that it will only provide audio in 16 bit signed integer or 32 bit float format, which emulates the behavior of the former BASS audio decoder.
An alternative solution would be to change the behavior of `TBassPlaybackStream` so that it can accept audio in any format, like the Mac/Linux `TGenericPlaybackStream` can. However, that would require a significant rewrite of `TBassPlaybackStream`, which would increase the risk …

Fix High Resolution Audio Support on Windows

---

src/screens/UScreenEditSub.pas

I don't need to see `ERROR: STOP` logged every single time a note (or sentence) ends when I'm working in the editor. I considered downgrading it to Debug but then it still doesn't really tell you much of value. Considering the all caps it reads like some kind of forgotten development comment.
(the git blame for this is misleading, bohning only changed the indentation but it was always there)

don't log ERROR: STOP the whole time in the editor

---

src/screens/UScreenScore.pas
src/screens/UScreenTop5.pas

Was making some local modifications when I noticed an unused function. Well, there was technically some commented-out place using it, and I think that's the first time I've seen three different ways of doing comments in that close proximity.
I did check that the screens still work in 2-screen mode. They're still as ugly as ever and some of the colors aren't quite right, but that's also happening on master.

remove unused TScreenScore.FillPlayer

---

src/media/UAudioPlaybackBase.pas

I delete* some of the bundled mp3's in my local build. I'm used to the error in the logs and never really paid attention to them, but with the recent removal of Bass for the audio decoding on Windows (#955), I started wondering why my _Linux_ logs were referring to `Bass` of all things in the first place:
```
ERROR:  Audio-file does not exist: "/usr/share/ultrastardx/sounds/null.mp3" [UAudio_FFmpeg]
STATUS: Could not open "/usr/share/ultrastardx/sounds/null.mp3" [TAudioPlayback_Bass.OpenStream]
```
TAudioPlayback_**Bass**.OpenStream
Turns out it's just a typo. A very confusing one because both UAudioPlaybackBase.pas and UAudioPlayback_Bass.pas are actual files.
\* = I actually rename stuff like `applause.mp3` to `null.mp3` in UMusic TSoundLibrary.LoadSounds, but the result is the same

typo: Bass is not the same as Base in the AudioPlayback context

---

src/base/UIni.pas

This has come up in the discord more than once. There really is no point in listing out that AReallyGoodPlayer has not only the highest score of 7550, but also 7530, 7480, 7440 and 7410. At least not in new installations.
For new installations, it will now only show the 7550 from AReallyGoodPlayer, so that AnAveragePlayer 6880, AnotherAveragePlayer 6700, PlayedForTheFirstTime 5500 and ICantSing 2300 can also be shown.
See also #725. The fact that I couldn't even figure out what the option was for while looking at the code should tell you a lot.

change top scores default to Player

---

src/media/UMediaCore_FFmpeg.pas

This PR fixes the FFmpeg error number to string conversion function. It uses an invalid method to convert between a C-style string and a Pascal string, which causes a crash when UDSX encounters an FFmpeg error and tries to output it to the `Error.log` file. This may occur if the audio file is corrupted in some way.
This has been a regression since #944. Before #944, this function still did not work properly, but it didn't cause USDX to crash. It just did nothing.

Fix Crash on Corrupt Audio Files

---

src/base/UGraphic.pas

without this patch my display looks like:
https://github.com/user-attachments/assets/57673b0d-023a-4b6b-9542-51be948a8af0
and it never updates. it might become completely black at some point (starting a song, usually) after which it stays black. the game is fully functional behind whatever it is doing, but navigating it completely blind is... challenging.
I've been using this patch for my local builds for a very long time already, but somehow I never needed it on a fresh git master until when I recently updated some things on my computer.
* I tested Windowed, Borderless and Fullscreen and they all work on _my_ machine
* I'll grab a CI artifact and test if Windows still works
* @DeinAlptraum can you test if this makes it also still work on _your_ machine?

newer SDLs appear to need this to get the windowsize

---

src/media/UAudioDecoder_FFmpeg.pas

The FFmpeg audio decoder has a function where it fills an audio stream with silence before the stream start time, if the first timestamp is greater than 0. An issue has been reported that this is causing crashes on such audio files since #944. The problematic statement is [here](https://github.com/UltraStar-Deluxe/USDX/blob/026cebb2996dbc6173873defdd60de9ffa602e01/src/media/UAudioDecoder_FFmpeg.pas#L1059). At that point in execution, `fAudioBuffer` is nil, which causes the crash.
#944 fixed the "StatusInfo" functionality of the packet queue, which had not been functional for many years (since FFmpeg 1.x was used). `fAudioBuffer` used to be an actual audio buffer, but since the codebase switched to use FFmpeg's `AVFrame` API, it's now implemented as a pointer to the `AVFrame` data buffer. …

Fix FFmpeg Start Silence Functionality

---

src/lib/bass/delphi/bass.pas

Compatibility flag for Delphi got removed during
the update to BASS 2.4.17, which caused compilation to fail on Windows when using MSYS2 and FPC.
This commit fixes that, so one can again build the game binary as instructed in the compilation guide.

Fix compiling on Windows.

---

src/base/UDraw.pas
src/lua/ULuaScreenSing.pas
src/screens/controllers/UScreenSingController.pas
src/screens/views/UScreenSingView.pas

Why: I was trying to refactor SingDrawLines and all the bitshifting stuff does not make this very readable. The performance impact should be negligible in the grand scheme of things.
It should all be 1:1 with the exception of UScreenSingView, part of that `if` statement just didn't make much sense.
I tested some modes with this and everything _appears_ to still be working, but it's probably a good idea if someone that uses party mode extensively tests+reviews this, because that's where the changes most prone to errors are.

refactor NotesVisible to be an array of booleans

---

game/languages/English.ini
src/base/UFiles.pas
src/base/UMusic.pas
src/base/USong.pas
src/media/UAudioPlaybackBase.pas
src/media/UMedia_dummy.pas
src/screens/UScreenCredits.pas
src/screens/UScreenEditSub.pas
src/screens/UScreenJukebox.pas
src/screens/UScreenScore.pas
src/screens/UScreenSong.pas
src/screens/controllers/UScreenSingController.pas

add karaoke mode via #INSTRUMENTALS or #KARAOKE tag, key to toggle
karaoke mode is K while playing.

add karaoke mode via #INSTRUMENTAL tag, key to toggle karaoke mode is K while playing.

---

src/base/UDraw.pas
src/base/UEditorLyrics.pas
src/base/UGraphic.pas
src/menu/UDisplay.pas
src/screens/UScreenEditSub.pas
src/screens/views/UScreenSingView.pas

Originally I wanted to use this PR to integrate SingDrawLines more into SingDraw and just call SingDrawNoteLines directly, since they're operating on the same "rectangles". Turns out it's not really a rectangle but only the left and right, and in _some_ cases, `Top` actually means `Bottom`.
In a future PR, I will probably just make a completely new function from scratch called `SingDrawNoteArea` (or something to that extent), which in turns calls another new function that draws everything note-area related that aren't golden notes for a specific player in a specific place. Would mean a few more `if` statements checking each frame whether to draw something or not, but be a lot better maintainable.
I will possibly also explore a `PlayersPerScreen` (or something) variable so everything …

Refactor singdrawlines

---

src/screens/UScreenEditSub.pas

This is not a general solution for the keybindings, but it removes a nuisance as SDLK_SLASH does not exist on all keyboards. SDLK_KP_DIVIDE was not used so far but would now be used as an alternative.

add KP_DIVIDE as an alternative to SLASH for keyboards that don't have

---

src/base/USong.pas

Currently, a song that has freestyle notes at the end only enters the highscore if the freestyle lines are also completed. this commit adds some backwards search for the last line that has a non-freestyle note. that line is now the last line for the decision whether or not to add the achieved score to the highscore or not.

Ignore freestyle notes for the last line computation

---

.github/workflows/main.yml

switch windows ci tag because windows-2019 does not exist anymore

---

src/screens/views/UScreenSingView.pas

The progress bar glitches in medley mode, starting negative, and sometimes completely off the screen. `TScreenSingController` and `TScreenSingView` are using different logic to calculate the start of the medley, which results in a discrepancy that causes the progress bar glitch. The progress bar drawing code in `TScreenSingView.DrawInfoLyricBar` is changed to use the `TScreenSingController` medley start/end values to eliminate the discrepancy.
It also draws sentence boxes for sentences that are not sung as part of the medley. That is fixed also.

Fix Time Bar for Medleys

---

DEVELOPMENT.md

The codebase was moved from svn to github in (afaik) 2016.
Generally I don't bother to even look at the svn history, but for example for 7d6a332db8127e626dd72ac91e55e4102afdc778 I wanted to know if it ever did anything, or what it was _supposed_ to do, and then it might be useful.
Emphasis on _might_ (in that particular case it wasn't) but having documented where it lives is at least better than nothing.

document where the old svn can be found

---

COMPILING.md
configure.ac
src/lib/ffmpeg-8.0/avcodec.pas
src/lib/ffmpeg-8.0/avformat.pas
src/lib/ffmpeg-8.0/avio.pas
src/lib/ffmpeg-8.0/avutil.pas
src/lib/ffmpeg-8.0/rational.pas
src/lib/ffmpeg-8.0/swresample.pas
src/lib/ffmpeg-8.0/swscale.pas
src/media/UVideo.pas

This PR adds support for FFmpeg 8.
Overall, the changes are fairly minimal. One public data field has been deprecated in the 8.0 release: `AVCodec.pix_fmts`. USDX uses this to query the pixel formats supported by a given video codec. The replacement is a new API function `avcodec_get_supported_config`. It's not required to replace it right now, but I decided to be proactive to avoid a break in a future release.
I set the version checks so these bindings will work for the entire 8.x release series (not just 8.0), as proposed in https://github.com/UltraStar-Deluxe/USDX/pull/985#issuecomment-2709046172. I think the FFmpeg developers have done a good job at keeping the ABI stable within each major release, and the strict minor and patch version checks are more of a hassle than they are worth. …

Support FFmpeg 8

---

dists/ultrastardx.desktop

At least GNOME shell is using the keyword field to match search strings against. All desktop files should contain keywords, to yield a satisfactory search experience.

Add keywords to desktop file

---

src/lib/midi/MidiIn.pas
src/media/UMidiInput.pas
src/screens/UScreenEditSub.pas
src/ultrastardx.dpr

Building on #820, this PR adds support on Windows for MIDI keyboards.
I tested this with a Native Instruments Komplete M32. Since this is extra input it is not necessary to enable the Piano Edit Mode, they MIDI keyboard keys just always work.

support midi keyboards in the usdx editor

---

src/base/UIni.pas
src/media/UAudioPlaybackBase.pas

as requested by @DoubleDee73. a config option for default instrumental.
in the config.ini
```
[Advanced]
DefaultSingMode=Instrumental # starts every song in instrumental mode
DefaultSingMode=Regular # default, behavior as it was
```
Did not add a config screen option to select this as we're running out of space.

add a config option for default instrumental

---

src/base/UNote.pas

so far usdx scanned for every beat through all lines and all notes, apparently as a workaround for buggy txts. i changed this to previous, current, next.
interestingly, it did not work with just current+next (0 points) as the comment suggested, my suspicion is, because the score is computed at the end of the line, that the line break --> change of current sentence happens just a few lines earlier, so unless checking the previous sentence, this cannot possibly work.
this now has a bit of tolerance while reducing the computation overhead for most txts significantly from checking 30+ lines to checking 3 lines.

don't check all sentences for every beat

---

src/base/USong.pas
src/screens/controllers/UScreenSingController.pas
src/screens/views/UScreenSingView.pas

This PR improves handling of song endings by ensuring that notes extending beyond the audio's actual length (or configured #END) are converted to freestyle notes. It also improves the SungToEnd logic.
* **TSong:**
* Add `AudioLength` param to `LoadOpenedSong`/`Analyse`.
* Notes past audio end become freestyle; logs a warning.
* **TScreenSingController:**
* Computes/passes `AudioEnd` to `Analyse` if available.
* Falls back gracefully if audio length is not yet known.
* **TScreenSingView:**
* `SungToEnd` so far only was set if the last note of the last non-freestyle line was completed. I fixed this: now it checks whether the in this last line the last non-freestyle note was completed for setting this flag. This is more important now as a too short audio may end within a line but would still …

Fix: Correctly handle song end - set unfinished notes after audio end to freestyle
