- game/languages/English.ini
New game modes added to language files, and old descriptions rewritten
> Adding Game Modes to language files

- Makefile.in
- README Mac OS X
- configure
- configure.ac
- dists/autogen/m4/fpc.m4
- src/config-darwin.inc
- src/lib/SDL2/SDL2_ttf.pas
Here is the stuff to makes USDX build on OSX using Brew.
As requested I've reintroduced fink stuff (but untested since not using it), there is a configure switch for fink or brew (and brew is default).
Also updated makefile, improved a bit the DMG stuff and updated README for build infos.
> [OSX] Fixes and build with brew

- configure
- configure.ac
Also, regenerate configure
Fixes #38
> Check fpc version in configure.ac

- src/base/UIni.pas
_(Note: This is not the most elegant solution. But hopefully one day it gets retwritten in a more cleaner version preventing devs using GetArrayIndex in a way it could crash, read the post. :wink: )_
In most/all cases, the config values are read by GetArrayIndex with the DefaultArray passed. Sometimes the array is directly accessed by passing the default value. This is likely not the problem as this would be noticed once you start the game (and the ini is read). However, with a bad configuration, the default value (and thus the safe one) is not used at all.
Take a look at "Screens=3". The config value is stored and read like:
`Screens := GetArrayIndex(IScreens, IniFile.ReadString('Graphics', 'Screens', IScreens[0]));`
With the IniFile.ReadString(..) expression, the return value is not …
> Prevent bad config values incorrectly pointing into array

- game/languages/English.ini
- installer/settings/settings.ini
Although the latest release includes a Gaelic.ini file, I can't select the language. I hope that this will fix it.
ETA: Restarting the program will load the language, but I guess these changes should still be made though so that I can get a proper language label.
My editor also cleaned up some trailing whitespaces.
> Added Scottish Gaelic (gd locale) to some ini files.

- src/base/UMusic.pas
> Bring AudioSampleSize array in sync with TAudioSampleFormat

- configure
- configure.ac
- dists/autogen/m4/fpc.m4
- src/lib/projectM/cwrapper/projectM-cwrapper.cpp
The first commit will fix issue #262. The other commits were necessary to build with --with-libprojectM on my Linux machine.
> some fixes for projectM support

- README.md
Hello! I added some notes to help people trying to compile and run the game on window 64-bit using Lazarus and fpc 64-bit versions, which was mentioned [here](https://github.com/UltraStar-Deluxe/USDX/issues/273). Thanks!
> Update README.md to add instructions to compile and run using Lazarus on Win 64-bit

- src/media/UVideo.pas
The last commit fixes the problems mentioned in a comment on ab5efd2ddbf6fc7dc32b34215a65d29225208ad6
> PTS calculation cleanups and a workaround

- README.md
These instructions worked for me after having trouble running released
app and then building.
MacOS High Sierra (10.13.1 (17B48))
> Update build instructions for MacOS (High Sierra)

- src/screens/controllers/UScreenSingController.pas
> Toggle the microphone oscilloscope in the SingScreen by pressing O.

- dists/linux/build.sh
- dists/linux/dl.sh
- dists/linux/launch.sh
Seems like `-shared-libgcc` started causing an access violation. Also, bumping dependencies.
> Fix Linux build, bump dependencies

- src/base/ULyrics.pas
> Improve kerning across syllables

- src/base/UMain.pas
- src/base/UWebcam.pas
- src/lib/openCV/opencv_core.pas
- src/lib/openCV/opencv_types.pas
Tested on Linux, please test on Windows before merging.
> Webcam fixes

- src/media/UAudioInput_Bass.pas
> Fix b20063bc2f3ac6a7e41ecbe18b9cf0272851fb2e

- src/base/UFont.pas
- src/lib/dglOpenGL/dglOpenGL.pas
- src/media/UVideo.pas
- src/media/UVisualizer.pas
- src/menu/UDisplay.pas
Fixes #510 as described there.
The calculated WidthScale and HeightScale values have been tested to be equal to the ones calculated with the old code (well, at least up two digits after the decimal point, I didn't print more).
> Get rid of libGLU

- Makefile.in
- configure.ac
- debian/control
- debian/rules
- debian/ultrastardx.links
- dists/gentoo/ultrastardx-1.1.0.ebuild
- dists/gentoo/ultrastardx-2017.8.0.ebuild
- dists/gentoo/ultrastardx-2020.4.0.ebuild
- dists/gentoo/ultrastardx-9999.ebuild
- src/base/UMusic.pas
- src/base/UPathUtils.pas
- src/media/UAudioPlayback_Bass.pas
These are a few small fixes that have accumulated on my disk. They should all be harmless.
> Various small fixes

- configure.ac
- src/lib/ffmpeg-4.0/avutil.pas
- src/lib/ffmpeg-5.0/avcodec.pas
- src/lib/ffmpeg-5.0/avformat.pas
- src/lib/ffmpeg-5.0/avio.pas
- src/lib/ffmpeg-5.0/avutil.pas
- src/lib/ffmpeg-5.0/rational.pas
- src/lib/ffmpeg-5.0/swresample.pas
- src/lib/ffmpeg-5.0/swscale.pas
- src/media/UAudioDecoder_FFmpeg.pas
- src/media/UMediaCore_FFmpeg.pas
- src/media/UVideo.pas
Many code changes. Barely tested.
Fixes #599
> Add support for FFmpeg 5.0

- src/base/UPlaylist.pas
- src/base/USong.pas
- src/base/USongs.pas
- src/screens/UScreenSong.pas
It took a significant amount of time to calculate this value for huge collections.
Fixes #320
> USongs: Cache VisibleIndex

- .gitignore
Part 1 of #636, this PR just ignores the `.idea` folder since not everyone likes Lazarus
> ignore intellij project folder

- src/media/UAudioPlayback_SDL.pas
- src/media/UMediaCore_SDL.pas
JACK insists on using float samples.
> Fix audio playback when using JACK SDL backend

- configure.ac
- src/lib/ffmpeg-6.0/avcodec.pas
- src/lib/ffmpeg-6.0/avformat.pas
- src/lib/ffmpeg-6.0/avio.pas
- src/lib/ffmpeg-6.0/avutil.pas
- src/lib/ffmpeg-6.0/rational.pas
- src/lib/ffmpeg-6.0/swresample.pas
- src/lib/ffmpeg-6.0/swscale.pas
- src/media/UAudioDecoder_FFmpeg.pas
- src/media/UVideo.pas
> Support FFmpeg6

- game/languages/English.ini
required to merge directly after #562
wiki page https://github.com/UltraStar-Deluxe/USDX/wiki/Controls is already updated
> document that the A key is a thing

- src/base/UDraw.pas
There's more refactoring yet to come in this file/function, but its perfectly mergeable in the current state, plus it keeps these PRs from becoming way too complex to review.
For reviewing, I recommend going commit-per-commit instead of looking at the entire diff at once.
_Yes_ I'm aware it 'introduces' some constants at the top of the function. And some of them are deliberately still sums, because the numbers on the left side are also in other places, and for the right hand side there's _at least_ also a `105` that's related to that `95` somewhere.
> Refactor singdraw

- configure.ac
- src/base/UTexture.pas
- src/lib/openCV3/ApiWrapper.cpp
These two commits allowed me to use a webcam on a 2005 Mac Mini.
> OpenCV fixes for old devices

- dists/linux/Dockerfile.in
- dists/linux/Makefile
- dists/linux/dl.sh
- dists/linux/dockerenv.sh
- dists/linux/tasks.sh
Depends on FFmpeg 6 PR. Will rebase after that one has been merged.
Updates everything we can update.
Enables a few more backends in SDL.
> Update AppImage dependencies

- src/lib/ffmpeg-4.0/swscale.pas
- src/lib/ffmpeg-5.0/swscale.pas
- src/lib/ffmpeg-6.0/swscale.pas
- src/media/UAudioDecoder_FFmpeg.pas
- src/media/UMediaCore_FFmpeg.pas
- src/media/UVideo.pas
I tested this only with FFmpeg 6.
> Fix memory leaks

- src/screens/UScreenSong.pas
> highlight only the actually selected song. fixes #666

- src/base/UImage.pas
thanks to @s09bQ5 for the fix!
This fixes the UI not displaying correctly in jukebox mode.
[Related topic](https://github.com/UltraStar-Deluxe/USDX/issues/717)
> fix:  Jukebox graphics not displaying correctly

- src/screens/controllers/UScreenSingController.pas
Fixes #764.
Broken since 983dc2f003466269eb84475defae3815405b1099
> Fix crash when video fails to load

- installer/settings/files_main_uninstall.nsh
Forgot to add this dll to the uninstaller when it was added in June.
> Uninstall libdav1d.dll as well

- src/media/UAudioPlayback_Bass.pas
- src/media/UAudioPlayback_SoftMixer.pas
this adds some additional logging to make it easier to figure out in bugreports which audio playback class is actually being used
> log which audio playback class is actually being used

- src/media/UAudioPlayback_SoftMixer.pas
this was introduced by #780 
one day I'm probably just going to add begin/end _everywhere_ before I even touch a file because it's really not obvious at all
> add missing begin/end statements

- src/screens/views/UScreenSingView.pas
This refactors a bunch of internals in UScreenSingView. _Shouldn't_ affect any behaviour.
> Refactor uscreensingview

- src/base/UPath.pas
- src/base/USong.pas
The first commit avoids opening and reading the txt file a second time during scanning.
The second commit avoids a redundant stat syscall on unix since the check has been added to the Free Pascal library.
> Avoid duplicate work during song scanning

- configure.ac
- src/lib/ffmpeg-7.0/avcodec.pas
- src/lib/ffmpeg-7.0/avformat.pas
- src/lib/ffmpeg-7.0/avio.pas
- src/lib/ffmpeg-7.0/avutil.pas
- src/lib/ffmpeg-7.0/rational.pas
- src/lib/ffmpeg-7.0/swresample.pas
- src/lib/ffmpeg-7.0/swscale.pas
- src/media/UAudioConverter.pas
- src/media/UAudioDecoder_FFmpeg.pas
The only necessary change was the switch to the new channel layout API.
Lots of structure elements got shifted around.
> Support FFmpeg 7,0

- src/base/USongs.pas
- src/screens/UScreenSong.pas
When using "Artist2" and tabs, you have one tabs (folder) per Artist, with the name of the Artist but there is no cover...
This Pull Request just use the cover of the first song of the artist as cover for the artist Tab.
> Use the cover of first song of the artist as cover for the "Artist2" Tab.

- src/base/UDraw.pas
- src/base/UNote.pas
> Make medly mode use normal mode difficulty setting

- .github/workflows/main.yml
This is a first attempt at a Github Actions CI. It currently successfully builds for Windows (32 btit), MacOS (Intel) and Linux (64bit).
There's still a few problems and open questions though:
- the Windows build and the portable upload runs for me, but the produced installer does not. Despite following the exact same steps for the installer as the current CI, it immediately crashes with the following error:
I do not know what causes this error (no, "run as admin" doesn't fix this) and googling it did not really help either. Since I have no experience with NSIS, maybe someone here knows?
- Trying to do the Linux build via the Docker image (like the AppVeyor CI does) just leads to a build failure with no error message somewhere in `tasks.sh`, see …
> Build Linux, MacOS and Windows platform in Github Actions CI

- dists/linux/Dockerfile.in
> Switch Linux docker build to Centos 7 archive mirrors

- src/lua/ULuaCore.pas
Hi all
Ever since Lua 5.2 released in 2011, people are encouraged to store the result of `require` locally, see http://lua-users.org/wiki/CompatibilityWithLuaFive section "Standardize calls to require()".
This bit me quite hard the other day when I tried to create a more involved party mode and could not get external modules to load. I was short of removing the custom require function since its apparent convenience breaks compatibility with any module which was written in the past ten years. But then I realized I could make it return the last module table which seems to solve the issue for everyone. 🙂
Kind Regards
Hermann
> Have TLua_CustomRequire put the module table on the Lua stack.

- src/screens/UScreenSong.pas
This fixes a crash on startup introduced by #851
> Set initial random song idx independently of CatSongs

- game/languages/Polish.ini
> Fix typo in Polish translation

- src/screens/UScreenPartyTournamentPlayer.pas
see #901
this allows people to set playernames in partymode again.
> allow to set player names in party->tournament again

- src/screens/UScreenSong.pas
> Esc Backspace issue W Tabs fix

- dists/linux/dl.sh
- dists/linux/tasks.sh
> AppImage: build with webp support

- src/base/UPathUtils.pas
> UPathUtils: Some logging improvements.

- src/base/UFiles.pas
- src/base/USong.pas
- src/screens/controllers/UScreenSingController.pas
Fixed #1026 this by removing the assignment and adding some more checks elsewhere
> Fix #1026 (editor incorrectly writes instrumental tag)

- src/base/UDLLManager.pas
- src/base/ULog.pas
- src/base/UParty.pas
- src/base/USong.pas
- src/lib/dglOpenGL/dglOpenGL.pas
- src/lua/UHookableEvent.pas
- src/lua/ULuaCore.pas
This fixes some spelling errors.
> Fix some spelling errors
